add transition between pages
double-slash-podcast/website pull request #91
Opened 2022-12-08 11:47 UTC by Corentin7301

Adding opacity transition between pages of the website.

2022-12-08 11:54 UTC, xlanex6 commented
@Corentin7301 

Thanks for your work 
is their a way to visualize the result before merging ? 
any  impact on performance ?

2022-12-08 12:05 UTC, Corentin7301 commented
@xlanex6 

No impact on performance, it's a Nuxt fonctionnality (https://nuxt.com/docs/getting-started/transitions).
Can't you see the result on the Netlify PR's build when you change the page?

2022-12-08 13:30 UTC, ipatate requested changes
Good idea 👍

2022-12-08 13:30 UTC, ipatate commented on assets/main.css
> +  transition: all 0.2s;
use tailwind please. @apply...

2022-12-08 13:30 UTC, ipatate commented on assets/main.css
> +  opacity: 0;
same.

2022-12-08 13:30 UTC, ipatate commented on layouts/default.vue
> +  <div class="min-h-screen bg-gradient-to-b from-darkPurple to-purpleDs">
the bg color isn't good for some pages
<img width="833" alt="Screenshot 2022-12-08 at 14 28 50" src="https://user-images.githubusercontent.com/46760/206458714-202d57d0-14f3-4603-bd3d-5774255d17af.png">

2022-12-08 13:49 UTC, Corentin7301 commented
Normally all is good. I've changed vanilla css to Tailwind style and I've updated bg color in all pages (can you test all the pages please?).

2022-12-08 14:38 UTC, ipatate commented
yeah, i'll look, thanks

2022-12-19 17:50 UTC, ipatate commented
Désolé pas eu le temps de regarder encore.

2023-09-01 16:05 UTC, closed without merging